### ISSUE TITLE
Moving forward

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#20]
Meta issue to collect tasks:

* [ ] Review all the code (already did a first sweep, but need another)
* [ ] Better test coverage
* [x] meta-tests to verify that nothing more is imported than intended
* [x] CI
* [ ] test visual result #133 #12
* [ ] More widgets (e.g. treeview) #111
* [ ] High-level fool-proof layout widgets (think dashboards) (there is plotLayout, but I do not like it too much
* [x] widget.flex signal should be a tuple
* [ ] Multilingual support (i.e. translations, and tools to do translations) #138
* [ ] Themes #139
* [x] PyScript methods for list, dict, str
* [x] Easy to use canvas widget
* [ ] More formal communication protocol (binary) #65

**Comment by almarklein** [comment]
All relevant points have an associated issue now, so we can close this.
